# This is a basic workflow to help you get started with Actions

name: Image Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Build Image
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: '.'
          builder_image: 'centos/php-72-centos7'
          tags: ${{ github.sha }}
          image: uploader

      - name: Push To quay
        run: |
          echo "Attempting docker login to: quay.io"
          echo "${{ secrets.QUAY_PASSWORD }}" | docker login -u "${{ secrets.QUAY_USERNAME }}" --password-stdin quay.io
          docker tag uploader:${{ github.sha }} quay.io/${{ secrets.QUAY_USERNAME }}/uploader:${{ github.sha }}
          docker push quay.io/${{ secrets.QUAY_USERNAME }}/uploader:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Delete and deploy
        run: |
          oc delete deployment --all
          oc delete routes --all
          oc delete services --all
          oc new-app --name uploader --docker-image=quay.io/${{ secrets.QUAY_USERNAME }}/uploader:${{ github.sha }}
          oc expose svc/uploader
